name: Delete deploys

on:
  pull_request:
    types: [closed]
  delete:
    branches:
      - '**'

jobs:
  delete_web:
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Delete Cloudflare Pages deployment
      run: |
        branch_name=${{ github.event.pull_request.head.ref }}
        npx wrangler pages project delete skygram-web-${branch_name}
